# Deployment for Makeline Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
spec:
  replicas: 1 # Single replica
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: makeline-service
          image: khad0062/makeline-service:v1 # Custom Makeline service image
          ports:
            - containerPort: 3001 # Makeline service listens on this port
          env: # Environment variables for configuration
            # - name: ORDER_QUEUE_HOSTNAME
            #   value: "bestbuy.servicebus.windows.net"
            # - name: ORDER_QUEUE_NAME
            #   value: "orders"
            # - name: USE_WORKLOAD_IDENTITY_AUTH
            #   value: "true"
            # - name: ORDER_QUEUE_TRANSPORT
            #   value: "tls"
            - name: ORDER_QUEUE_URI
              value: "amqps://bestbuycanada.servicebus.windows.net"
            - name: ORDER_QUEUE_PORT
              value: "5671"
            - name: ORDER_QUEUE_USERNAME
              value: "listener"
            - name: ORDER_QUEUE_PASSWORD
              value: "waSqNV+j1vmYS7V51zWeZ3A7f1ZL5kYrf+ASbLoFQ3o"
            - name: ORDER_QUEUE_TRANSPORT
              value: "tls"
            - name: ORDER_QUEUE_NAME
              value: "orders"
            - name: ORDER_DB_URI
              value: "mongodb://mongodb:27017" # MongoDB connection string
            - name: ORDER_DB_NAME
              value: "orderdb" # Database name
            - name: ORDER_DB_COLLECTION_NAME
              value: "orders" # Collection name
          resources: # Resource requests and limits
            requests:
              cpu: 1m
              memory: 6Mi
            limits:
              cpu: 5m
              memory: 20Mi
          startupProbe: # Initial health check
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 10
            periodSeconds: 5
          readinessProbe: # Ready status probe
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe: # Ongoing health check
            httpGet:
              path: /health
              port: 3001
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 3
---
# Service for Makeline Service
apiVersion: v1
kind: Service
metadata:
  name: makeline-service
spec:
  type: ClusterIP # Internal cluster service
  ports:
    - name: http
      port: 3001 # Service port
      targetPort: 3001
  selector:
    app: makeline-service
