apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
type: Opaque
data:
  OPENAI_API_KEY: "eHdTeFlnMzZTbXBmZmhEMUxqdEZqNmNKT0RZcUR4dnNJVHZWWWpmVWh3dXQ3VFMzMFdKQUpRUUo5OUJEQUNmaE1rNVhKM3czQUFBQkFDT0duaEcz"

---
apiVersion: v1
kind: Secret
metadata:
  name: service-bus-secret-key
type: Opaque
data:
  SERVICE_BUS_SENDER_SECRET: "eE9ndEp4eW1Sa1Q3VGJkU2EzdnpaSndRMzJSbWxHdk96K0FTYlA0cjFhUT0="
  SERVICE_BUS_LISTENER_SECRET: "bGpOZ3E4RlFmRkNQald6VE0ySUhVVWw0R0ZLdkJrVGRhK0FTYlAvYmQ5WT0="